apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: {{ .Values.webapp.port }}
      targetPort: {{ .Values.webapp.port }}
  type: ClusterIP
